import { useParams } from 'react-router-dom';
import { QRCodeSVG } from 'qrcode.react';
import { Check, Factory, Leaf, Users } from 'lucide-react';
import type { Aggregates, PublicState, RoundStats, Strategy } from '../shared/model';
import { commitments, discussions, expansion, plans, pollChoices, pollQuestion, roundTitles, scenarios, strategyInfo } from '../shared/content';
import { Busy, City, NetworkNotice, Priorities } from './components';
import { usePolling } from './api';
function Bars({ stats, options }: { stats: RoundStats; options: { id: string; title: string }[] }) {
  const items = [...(stats.items ?? [])].sort((a, b) => b.count - a.count);
  return stats.count ? <div className={`result-bars ${options.length > 4 ? 'many-bars' : ''}`}>{items.map(item => <div key={item.id} className="result-bar"><div className="bar-label"><span>{options.find(o => o.id === item.id)?.title}</span><strong>{Math.round(item.percent)}<small>%</small></strong></div><div className="track"><div style={{ width: `${item.percent}%` }}/></div></div>)}</div> : <div className="empty-results">No decisions were submitted for this round.</div>;
}
function FundingResult({ stats }: { stats: RoundStats }) {
  if (!stats.count) return <div className="empty-results">No funding plans were submitted.</div>;
  const city = stats.average ?? 0; return <div className="funding-result"><div className="funding-totals"><div><span>City / taxpayers</span><strong>${(city / 1e6).toFixed(1)}<small>M</small></strong></div><div><span>Company</span><strong>${((8e6 - city) / 1e6).toFixed(1)}<small>M</small></strong></div></div><div className="funding-split"><div style={{ width: `${city / 8e6 * 100}%` }}/></div><p>$8 million total cleanup investment</p></div>;
}
function PowerResult({ stats }: { stats: RoundStats }) {
  if (!stats.count) return <div className="empty-results">No community-power decisions were submitted.</div>;
  const maximum = Math.max(...(stats.bins ?? [1]), 1); return <div className="power-result"><div className="histogram" role="img" aria-label={`Distribution of community power choices. Class average ${Math.round(stats.average ?? 0)} out of 100.`}>{stats.bins?.map((value, i) => <div key={i} style={{ height: `${value / maximum * 100}%` }}><span>{value || ''}</span></div>)}<div className="average-marker" style={{ left: `${Math.max(8, Math.min(92, stats.average ?? 50))}%` }}><span>Class average</span><i/></div></div><div className="spectrum-labels"><span>Consultation</span><span>Shared influence</span><span>Community approval</span></div></div>;
}
function RoundResults({ s }: { s: PublicState }) {
  const stats = s.aggregates?.rounds[s.round] ?? { count: 0 };
  return <><p className="eyebrow">Round {s.round} · our class decision</p><h1>{s.round === 2 ? 'Who should pay?' : s.round === 3 ? 'What did our class require?' : s.round === 4 ? 'Who gets power?' : s.round === 5 ? 'What comes next for Riverton?' : 'How should we rebuild?'}</h1><div className="projector-chart">{s.round === 2 ? <FundingResult stats={stats}/> : s.round === 4 ? <PowerResult stats={stats}/> : <Bars stats={stats} options={s.round === 1 ? plans : s.round === 3 ? commitments : expansion}/>}</div><div className="discussion"><span>Discuss</span><p>{discussions[s.round - 1]}</p></div></>;
}
function ClassProfile({ a }: { a: Aggregates }) {
  return <><p className="eyebrow">Five decisions. One community.</p><h1>How did our class<br/>rebuild Riverton?</h1>{a.completed ? <div className="profile-columns"><div><h3>Our strategies</h3><Bars stats={{ count: a.completed, items: (Object.keys(a.strategies) as Strategy[]).map(id => ({ id, count: a.strategies[id], percent: a.strategies[id] / a.completed * 100 })) }} options={Object.entries(strategyInfo).map(([id, info]) => ({ id, title: info.title }))}/><p className="projector-note">Based on {a.completed} complete strategies</p></div><div><h3>Our class priorities</h3><Priorities values={a.priorities}/><p className="projector-note">An interpretation of our choices, without right or wrong outcomes.</p></div></div> : <p className="empty-results">No complete strategies yet. Each student needs all five decisions.</p>}</>;
}
function CaseStudy({ valley = false }: { valley?: boolean }) {
  return <div className="case-study"><div><p className="eyebrow">{valley ? 'Milwaukee, Wisconsin' : 'Pullman, Chicago'}</p><h1>{valley ? <>Menomonee<br/>Valley.</> : <>Method.<br/>South Side Soapbox.</>}</h1><p className="case-label">{valley ? 'Public-private-community redevelopment' : 'Business-driven redevelopment with public support'}</p><p className="case-intro">{valley ? 'A damaged industrial landscape became a place for work, recreation, and restored natural resources.' : 'A sustainable manufacturing facility brought new activity to previously industrial land.'}</p></div><div className="case-features">{(valley ? ['Environmental cleanup', 'Public infrastructure', 'Private investment & jobs', 'Community & nonprofit involvement', 'Restoration of industrial land'] : ['Private manufacturing investment', 'Sustainable facility design', 'Brownfield redevelopment', 'Manufacturing jobs', 'Public redevelopment support & incentives']).map(text => <div key={text}><Check size={25}/><span>{text}</span></div>)}</div><div className="case-lesson"><span>Ethical lesson</span><p>{valley ? 'Historic environmental damage may require government intervention while private investment creates future economic opportunity.' : 'A business can treat the surrounding community as a stakeholder rather than simply choosing the cheapest location available.'}</p></div></div>;
}
function Comparison({ a }: { a: Aggregates }) {
  return <><p className="eyebrow">Different paths. Shared questions.</p><h1>Who takes responsibility?</h1><div className="comparison-grid"><div><Factory size={32}/><h2>Method / Pullman</h2><dl><dt>Business</dt><dd>High</dd><dt>Government</dt><dd>Moderate</dd><dt>Community</dt><dd>Moderate</dd></dl></div><div><Leaf size={32}/><h2>Menomonee Valley</h2><dl><dt>Business</dt><dd>High</dd><dt>Government</dt><dd>High</dd><dt>Community</dt><dd>High</dd></dl></div><div className="class-comparison"><Users size={32}/><h2>Our class</h2><Priorities values={a.priorities}/></div></div><p className="projector-note">Illustrative teaching comparison. These levels are not scientific measurements or ratings of the actual projects.</p></>;
}
function Scene({ s }: { s: PublicState }) {
  const joinURL = `${location.origin}/join/${s.code}`;
  if (s.screen === 'lobby') return <div className="projector-lobby"><div><p className="eyebrow">Rebuild Riverton</p><h1>You’re now on the<br/>redevelopment<br/>committee.</h1><p className="lobby-instruction">Take out your phone.<br/>Your city needs a decision.</p><div className="people-joined"><span className="live-dot"/><strong>{s.joined}</strong><span>people joined</span></div></div><div className="qr-panel"><div className="qr-paper"><QRCodeSVG value={joinURL} size={310} level="M" marginSize={4}/></div><span className="join-url">{location.host}</span><strong className="projector-code">{s.code}</strong><span>Scan to join, or enter the code at the address above.</span></div></div>;
  if (s.screen === 'intro') return <div className="projector-intro"><div><p className="eyebrow">Welcome to Riverton</p><h1>A city to rebuild.<br/>A future to decide.</h1><p>Can you rebuild an industrial community without repeating the mistakes of its past?</p><div className="intro-stat-grid"><div><strong>42,000</strong><span>residents</span></div><div><strong>$41,000</strong><span>median household income</span></div><div><strong>180</strong><span>acres of industrial land</span></div><div><strong>70+</strong><span>years of manufacturing</span></div></div></div><div><City/><p className="intro-mission">Balance economic growth, environmental protection, jobs, business investment, public spending, and community influence.</p></div></div>;
  if (s.screen === 'round') return <div className="projector-voting"><div><p className="eyebrow">Round {s.round} of 5 {s.round === 5 ? '· 5 years later' : ''}</p><h1>{roundTitles[s.round - 1]}</h1><p className="projector-scenario">{scenarios[s.round - 1]}</p>{s.round === 5 && <div className="expansion-facts"><span><strong>+200</strong> jobs</span><span><strong>+$75M</strong> investment</span></div>}</div><div className="vote-counter"><strong>{s.submitted}<span> / {s.joined}</span></strong><p>decisions submitted</p><div className="track"><div style={{ width: `${s.joined ? s.submitted / s.joined * 100 : 0}%` }}/></div><span className="voting-label">{s.votingOpen ? 'Make your decision on your phone.' : s.submitted ? 'Voting is closed. The reveal is next.' : 'Voting opens in a moment.'}</span></div></div>;
  if (s.screen === 'round-results') return <RoundResults s={s}/>;
  if (s.screen === 'class-profile' && s.aggregates) return <ClassProfile a={s.aggregates}/>;
  if (s.screen === 'real-world') return <div className="real-world-reveal"><p className="eyebrow">From simulation to reality</p><h1>Riverton was fictional.<br/>These decisions<br/>weren’t.</h1><p>Two communities. Two approaches to redevelopment.</p><City progress={5}/></div>;
  if (s.screen === 'method') return <CaseStudy/>;
  if (s.screen === 'valley') return <CaseStudy valley/>;
  if (s.screen === 'comparison' && s.aggregates) return <Comparison a={s.aggregates}/>;
  if (s.screen === 'poll') return <div className="projector-poll"><p className="eyebrow">One final question</p><h1>{pollQuestion}</h1><div className="poll-waiting"><strong>{s.pollSubmitted} / {s.joined}</strong><span>responded</span><p>{s.votingOpen ? 'Yes. No. It depends. Answer on your phone.' : 'Voting is closed. The reveal is next.'}</p></div></div>;
  if (s.screen === 'poll-results') return <div className="projector-poll-results"><p className="eyebrow">Our final reflection</p><h1>Legal does not automatically<br/>mean ethical.</h1><Bars stats={s.aggregates?.poll ?? { count: 0 }} options={pollChoices}/><div className="ethics-connections"><span>Business as a service to humankind</span><span>Business as a contemporary community</span></div><div className="discussion"><p>Where should the ethical responsibility of business end?</p></div></div>;
  return <div className="closing-scene"><Leaf size={52}/><p className="eyebrow">Rebuild Riverton</p><h1>Where should the<br/>ethical responsibility<br/>of business end?</h1><p>Legal does not automatically mean ethical.</p><div className="ethics-connections"><span>Business as a service to humankind</span><span>Business as a contemporary community</span></div></div>;
}
export default function Projector() {
  const code = (useParams().code ?? '').toUpperCase(); const { data, error, refresh } = usePolling<PublicState>(`sessions/${code}/display`, undefined, 1000);
  return <div className={`projector-shell greenery-${data?.round ?? 0}`}><div className="projector-stage"><NetworkNotice error={error} retry={refresh}/>{data ? <div className="projector-scene" key={`${data.epoch}-${data.screen}-${data.round}`}><Scene s={data}/></div> : <Busy/>}<footer className="projector-footer"><span>Rebuild Riverton</span><span>{data?.screen === 'lobby' ? 'Environmental justice · A live classroom simulation' : 'Growth. Responsibility. Community.'}</span><span>{data?.code ?? code}</span></footer></div></div>;
}
