import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Check, ChevronLeft, ChevronRight, Leaf, Minus, Plus, Users } from 'lucide-react';
import type { Choice, PublicState } from '../shared/model';
import { commitments, expansion, plans, pollChoices, pollQuestion, roundTitles, scenarios, strategyInfo } from '../shared/content';
import { Busy, Locked, NetworkNotice, Priorities } from './components';
import { RequestError, request, usePolling } from './api';
function RoundInteraction({ round, submit, busy }: { round: number; submit: (value: Choice) => void; busy: boolean }) {
  const [plan, setPlan] = useState(0); const [city, setCity] = useState(4_000_000); const [selected, setSelected] = useState<string[]>([]); const [power, setPower] = useState(50); const [final, setFinal] = useState('');
  const funding = (value: number) => setCity(Math.max(0, Math.min(8_000_000, value)));
  if (round === 1) return <><div className="proposal-strip" onTouchStart={e => { e.currentTarget.dataset.touchX = String(e.touches[0].clientX); }} onTouchEnd={e => { const delta = e.changedTouches[0].clientX - Number(e.currentTarget.dataset.touchX); if (Math.abs(delta) > 55) setPlan(p => Math.max(0, Math.min(2, p + (delta < 0 ? 1 : -1)))); }}><div className="proposal" key={plan}><div className="proposal-heading"><span>{plans[plan].tag}</span><Leaf size={21}/></div><h2>{plans[plan].title}</h2><p>{plans[plan].body}</p><ul>{plans[plan].benefits.map(b => <li key={b}><Check size={17}/>{b}</li>)}</ul><div className="tradeoff"><span>The tradeoff</span><p>{plans[plan].tradeoff}</p></div></div></div><div className="proposal-navigation"><button aria-label="Previous proposal" disabled={plan === 0} onClick={() => setPlan(p => p - 1)}><ChevronLeft/></button><div role="group" aria-label="Choose proposal">{plans.map((p, i) => <button key={p.id} aria-label={p.title} aria-pressed={plan === i} className={plan === i ? 'active' : ''} onClick={() => setPlan(i)}>{p.tag.replace('Plan ', '')}</button>)}</div><button aria-label="Next proposal" disabled={plan === 2} onClick={() => setPlan(p => p + 1)}><ChevronRight/></button></div><button className="primary full" disabled={busy} onClick={() => submit(plans[plan].id)}>Choose {plans[plan].title.toLowerCase()}</button></>;
  if (round === 2) return <><div className="funding-card"><p className="eyebrow">Who should pay?</p><div className="funding-amounts"><div><span>City / taxpayers</span><strong>${(city / 1e6).toFixed(2)}M</strong></div><div><span>Company</span><strong>${((8e6 - city) / 1e6).toFixed(2)}M</strong></div></div><input type="range" aria-label="City contribution" aria-valuetext={`City ${city.toLocaleString()} dollars, company ${(8e6 - city).toLocaleString()} dollars`} min={0} max={8_000_000} step={1} value={city} onChange={e => funding(Number(e.target.value))}/><div className="spectrum-labels"><span>Company pays all</span><span>City pays all</span></div><div className="funding-adjust"><button aria-label="Decrease city contribution by 250000 dollars" onClick={() => funding(city - 250_000)}><Minus/></button><label>City contribution<input type="number" min={0} max={8_000_000} step={1} value={city} onChange={e => funding(Math.round(Number(e.target.value)))}/></label><button aria-label="Increase city contribution by 250000 dollars" onClick={() => funding(city + 250_000)}><Plus/></button></div><p className="budget-total">Total cleanup budget: $8,000,000</p></div><button className="primary full" disabled={busy} onClick={() => submit(city)}>Lock in funding plan</button></>;
  if (round === 3) return <><div className="agreement"><div className="agreement-title"><strong>Your agreement</strong><span>{selected.length} / 2 commitments</span></div>{selected.length ? selected.map(id => <button key={id} className="agreement-item" onClick={() => setSelected(s => s.filter(x => x !== id))}><Check size={16}/>{commitments.find(c => c.id === id)!.title}<span>×</span></button>) : <p>Choose exactly two commitments below.</p>}</div><div className="commitment-grid">{commitments.filter(c => !selected.includes(c.id)).map(c => <button key={c.id} className="commitment" disabled={selected.length === 2} onClick={() => setSelected(s => [...s, c.id])}><Plus size={19}/><strong>{c.title}</strong><span>{c.body}</span></button>)}</div><button className="primary full" disabled={selected.length !== 2 || busy} onClick={() => submit(selected)}>Lock in your agreement</button></>;
  if (round === 4) return <><div className="power-card"><Users size={36}/><h2>{power < 33 ? 'Consultation' : power > 66 ? 'Community approval' : 'Shared influence'}</h2><p>{power < 33 ? 'Residents provide input. Government and businesses make final decisions.' : power > 66 ? 'Major development requires significant support from affected residents.' : 'Community representatives formally participate in redevelopment decisions.'}</p><input type="range" min={0} max={100} step={1} value={power} aria-label="Resident decision-making power" aria-valuetext={`${power} percent along the spectrum from consultation to community approval`} onChange={e => setPower(Number(e.target.value))}/><div className="spectrum-labels"><span>Consultation</span><span>Community approval</span></div><p className="range-help">Drag to any point. With a keyboard, use the arrow keys.</p></div><button className="primary full" disabled={busy} onClick={() => submit(power)}>Set the community’s role</button></>;
  return <><div className="expansion-facts"><span><strong>+200</strong> jobs</span><span><strong>+$75M</strong> investment</span></div><div className="decision-grid">{expansion.map(c => <button key={c.id} aria-pressed={final === c.id} className={`decision ${final === c.id ? 'selected' : ''}`} onClick={() => setFinal(c.id)}><span className="radio-dot"/><div><strong>{c.title}</strong><p>{c.body}</p></div></button>)}</div><p className="final-note">Final decision. Once submitted, your Riverton strategy is complete.</p><button className="primary full" disabled={!final || busy} onClick={() => submit(final)}>Complete your strategy</button></>;
}
function StudentSession({ code, token }: { code: string; token: string }) {
  const { data, error, fatal, refresh } = usePolling<PublicState>(`sessions/${code}/state`, token);
  const [sending, setSending] = useState(false); const [submitError, setSubmitError] = useState(''); const [locked, setLocked] = useState<number>();
  useEffect(() => { setLocked(undefined); setSubmitError(''); }, [data?.round, data?.epoch, data?.screen]);
  async function submit(value: Choice, poll = false) {
    if (!data) return; setSending(true); setSubmitError('');
    try { await request(`sessions/${code}/${poll ? 'final-poll' : 'responses'}`, token, poll ? { value, epoch: data.epoch } : { round: data.round, value, epoch: data.epoch }); setLocked(poll ? 6 : data.round); refresh(); }
    catch (e) { setSubmitError(e instanceof RequestError ? e.message : 'Could not confirm your decision. Retry; duplicate answers will stay locked.'); refresh(); } finally { setSending(false); }
  }
  if (!data || fatal) return <><NetworkNotice error={error} retry={refresh}/>{!fatal && <Busy/>}{fatal && <a className="quiet-link" href="/">Return to join page</a>}</>;
  const ownAnswer = data.answers?.[data.round];
  let view;
  if (data.screen === 'poll') view = data.pollAnswer || locked === 6 ? <Locked poll/> : <div className="round-content"><p className="eyebrow">One final question</p><h1 className="poll-question">{pollQuestion}</h1><div className="decision-grid">{pollChoices.map(c => <button className="decision" disabled={sending || !data.votingOpen} key={c.id} onClick={() => submit(c.id, true)}><strong>{c.title}</strong><ChevronRight/></button>)}</div><p>This reflection does not change your strategy.</p>{!data.votingOpen && <p>Voting has closed. Watch the projector for the reveal.</p>}</div>;
  else if (data.screen === 'ended' || data.screen === 'poll-results') view = <div className="waiting-panel"><Leaf size={42}/><h1>Where should the ethical responsibility of business end?</h1><p>Legal does not automatically mean ethical.</p><p>Thank you for helping rebuild Riverton.</p>{data.result && <div className="result-summary">Your strategy: {strategyInfo[data.result.strategy].title}</div>}</div>;
  else if (data.result) view = <div className="personal-result"><p className="eyebrow">Your Riverton strategy</p><Leaf size={34}/><h1>{strategyInfo[data.result.strategy].title}</h1><p>{strategyInfo[data.result.strategy].description}</p><h3>Your priorities</h3><Priorities values={data.result.priorities}/><p className="fine-print">A reflection of your choices, with no right or wrong outcome. Watch the projector for our class’s story.</p></div>;
  else if (data.screen === 'round') view = ownAnswer !== undefined || locked === data.round ? <Locked/> : !data.votingOpen ? <div className="waiting-panel"><p className="eyebrow">Round {data.round}</p><h1>{roundTitles[data.round - 1]}</h1><p>Voting is {data.submitted ? 'closed' : 'about to open'}. Watch the projector.</p></div> : <div className="round-content" key={`${data.epoch}-${data.round}`}><div className="round-step"><span>Decision {data.round} of 5</span><div>{[1, 2, 3, 4, 5].map(r => <i key={r} className={r <= data.round ? 'filled' : ''}/>)}</div></div>{data.round === 5 && <p className="time-jump">5 years later</p>}<h1>{roundTitles[data.round - 1]}</h1><p className="scenario">{scenarios[data.round - 1]}</p><RoundInteraction key={`${data.epoch}-${data.round}`} round={data.round} submit={submit} busy={sending}/></div>;
  else if (data.screen === 'intro') view = <div className="student-intro"><p className="eyebrow">Welcome to the redevelopment committee</p><h1>A city at a crossroads.</h1><p>Riverton has 42,000 residents, 180 acres of former industrial land, and more than 70 years of manufacturing history.</p><div className="issue-tags">{['Contaminated land', 'Vacant properties', 'Pollution concerns', 'Unemployment', 'Limited investment'].map(x => <span key={x}>{x}</span>)}</div><h2>Your mission</h2><p>Balance economic growth, environmental protection, jobs, investment, public spending, and community influence.</p><p className="fine-print">The presenter will open your first decision.</p></div>;
  else if (data.screen === 'round-results') view = <div className="waiting-panel"><Check size={38}/><h1>Look up.<br/>Riverton has spoken.</h1><p>The presenter is revealing the class results. Your next decision will appear here.</p></div>;
  else view = <div className="waiting-panel"><span className="seal"><Check size={34}/></span><p className="eyebrow">You’re in</p><h1>You’re on the<br/>committee.</h1><p>Waiting for the simulation to begin…</p><div className="pulse-line"/><p className="fine-print">No names. No right answers. Just your decisions.</p></div>;
  return <><NetworkNotice error={error} retry={refresh}/>{view}{submitError && <p className="error submission-error" role="alert">{submitError}</p>}</>;
}
export default function Student() {
  const code = (useParams().code ?? '').toUpperCase(); const [token, setToken] = useState<string>(); const [error, setError] = useState(''); const [retry, setRetry] = useState(0);
  useEffect(() => {
    let active = true; setToken(undefined); setError('');
    // StrictMode effect replay shares the same pending join, avoiding two seats.
    const key = `riverton.participant.${code}`; const existing = localStorage.getItem(key);
    const join = joins.get(code) ?? request<{ participantToken: string }>(`sessions/${code}/join`, existing ?? undefined, {});
    joins.set(code, join);
    join.then(result => { localStorage.setItem(key, result.participantToken); if (active) setToken(result.participantToken); }).catch(e => { if (active) setError(e instanceof RequestError ? e.message : 'Unable to join. Check your connection and try again.'); }).finally(() => joins.delete(code));
    return () => { active = false; };
  }, [code, retry]);
  return <div className="student-shell"><header className="student-header"><a href="/">Rebuild Riverton</a><span>{code}</span></header><main>{token ? <StudentSession code={code} token={token}/> : error ? <div className="waiting-panel"><h1>Let’s get you in.</h1><p role="alert">{error}</p><button className="primary" onClick={() => setRetry(r => r + 1)}>Try again</button><a className="quiet-link" href="/">Enter another class code</a></div> : <Busy/>}</main><footer className="student-footer">One community. Your voice.</footer></div>;
}
const joins = new Map<string, Promise<{ participantToken: string }>>();
